### ISSUE TITLE
Apparant version reset breaks existing installations

### ISSUE THREAD

**Issue by j-maas** [tricycle/elm-embed-youtube#3]
Not to worry too much, but I my installation broke (see https://github.com/Y0hy0h/recipe-box/runs/2801631874) and I think it is because the version was set back to 1.0.0. It appears that the user was renamed, which GitHub actually handles fine through a redirect, but existing applications that had this package installed won't find the correct version to download.

This can be handled by the users of this package by [replacing the dependency](https://github.com/Y0hy0h/recipe-box/commit/4ba3ebac26b044be10d812c143fc433c92555698) on `"tricycle/elm-embed-youtube": "1.1.2"` with `"bellroy/elm-embed-youtube": "1.0.0"`.

So I wanted to open this issue in case anyone else stumbles upon this. ;)

**Comment by michaelwebb76** [comment]
Sorry about that @Y0hy0h - unfortunately this was an organisation rename that was years overdue and there's no other way to handle this in the Elm package ecosystem 😢

**Comment by j-maas** [comment]
It's not that tragic. :)

Would you consider adding a disclaimer to the README of the obsolete package, so that if someone finds it in the package search, they know they should use this package instead?

**Comment by michaelwebb76** [comment]
Can I even do that? Un-renaming the organisation is not an option, and I'm not aware of any other way to edit the package?

**Comment by michaelwebb76** [comment]
FWIW If I'd known that was going to happen I would have done that proactively, but I don't think I can fix it now :-/

**Comment by j-maas** [comment]
Oh, I didn't understand that you don't have access anymore. 😄
Yeah, then there's not much you can do. 👍
